In [3]:
import numpy as np
# Crear una matriz bidimensional 3x3
matriz_3x3 = np.arange(9).reshape(3, 3)
# Imprime la matriz "matriz_3x3" para verificar su contenido.
print(matriz_3x3)
# Crear una matriz identidad de 6x6
matriz_identidad = np.identity(6)
# Imprimir la matriz identidad
print(matriz_identidad)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
